version: '3.8'

services:

  portainer:
    image: portainer/portainer-ce:2.9.3-alpine
    hostname: portainer
    command: -H tcp://tasks.agent:9001 --tlsskipverify
    networks:
      - agent_net
      - public
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - "node.role == manager"
          - "node.hostname == main-1"
      resources:
        limits:
          cpus: '1'
          memory: 2G
        reservations:
          cpus: '0.2'
          memory: 256M
      labels:
        - "traefik.enable=true"
        # Router
        - "traefik.http.routers.portainer.rule=Host(`portainer.silkky.cloud`)"
        - "traefik.http.routers.portainer.entrypoints=websecure"
        - "traefik.http.routers.portainer.tls=true"
        - "traefik.http.routers.portainer.service=portainer-service"
        # Service
        - "traefik.http.services.portainer-service.loadbalancer.server.port=9000"
    volumes:
      - portainer_data:/data

  agent:
    image: portainer/agent:2.9.3-alpine
    networks:
      - agent_net
    deploy:
      mode: global
      placement:
        constraints:
          - "node.platform.os == linux"
          - "node.role == manager"
      resources:
        limits:
          cpus: '0.25'
          memory: 50M
        reservations:
          cpus: '0.05'
          memory: 15M
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/volumes:/var/lib/docker/volumes

networks:
  public:
    external: true
  agent_net:
    driver: overlay
    attachable: true
    internal: true
    driver_opts:
      encrypted: "true"
      com.docker.network.driver.mtu: 1450

volumes:
  portainer_data: