# This is not high availability, the 'authelia-data' directory must be created manually with the users.yml backend.
version: '3.8'

services:

  authelia:
    image: authelia/authelia:4.34.5
    hostname: authelia
    networks:
      - backend
      - public
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - "node.hostname == main.web01.hel.hcloud.silkky.cloud"
      resources:
        limits:
          cpus: '0.5'
          memory: 1G
        reservations:
          cpus: '0.1'
          memory: 100M
      labels:
        - "traefik.enable=true"
        # Router
        - "traefik.http.routers.authelia.rule=Host(`auth.silkky.cloud`)"
        - "traefik.http.routers.authelia.entrypoints=websecure"
        - "traefik.http.routers.authelia.tls=true"
        - "traefik.http.routers.authelia.service=authelia-service"
        # Service
        - "traefik.http.services.authelia-service.loadbalancer.server.port=9091"
        # Authentication middleware
        - "traefik.http.middlewares.authelia.forwardauth.address=http://authelia:9091/api/verify?rd=https://auth.silkky.cloud"
        - "traefik.http.middlewares.authelia.forwardauth.trustForwardHeader=true"
        - "traefik.http.middlewares.authelia.forwardauth.authResponseHeaders=Remote-User,Remote-Groups,Remote-Name,Remote-Email"
    volumes:
      - ./authelia-data:/data
    configs:
      # Authelia config
      - source: authelia-config-004
        target: /config/configuration.yml
    secrets:
      # JWT secret key
      - source: authelia-jwt
        target: jwt.key
        mode: 0600
      # Storage encryption key
      - source: authelia-encryption-key
        target: storage.key
        mode: 0600
      # Session secret
      - source: authelia-session-key
        target: session.key
        mode: 0600
      # Mailer password
      - source: mailgun-noreply-password
        target: mail-password.key
        mode: 0600
    environment:
      - AUTHELIA_JWT_SECRET_FILE=/run/secrets/jwt.key
      - AUTHELIA_STORAGE_ENCRYPTION_KEY_FILE=/run/secrets/storage.key
      - AUTHELIA_SESSION_SECRET_FILE=/run/secrets/session.key
      - AUTHELIA_NOTIFIER_SMTP_PASSWORD_FILE=/run/secrets/mail-password.key

  redis:
    image: redis:6.2.6-alpine
    hostname: redis
    networks:
      - backend
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - "node.hostname == main.web01.hel.hcloud.silkky.cloud"
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
        reservations:
          cpus: '0.1'
          memory: 50M
    volumes:
      - redis_database:/data

networks:
  public:
    external: true
  backend:
    driver: overlay
    internal: true
    driver_opts:
      com.docker.network.driver.mtu: 1450

volumes:
  redis_database:

configs:
  authelia-config-004:
    file: ./authelia/configuration.yml

secrets:
  authelia-jwt:
    external: true
  authelia-encryption-key:
    external: true
  authelia-session-key:
    external: true
  mailgun-noreply-password:
    external: true