theme: dark

log:
  level: info

server:
  host: 0.0.0.0
  port: 9091

access_control:
  default_policy: deny
#  networks:
#    - name: main.web
#      networks:
#        - 65.108.90.195
#        - 65.108.95.18
#        - 65.108.90.241

  rules:
    - domain: ["portainer.silkky.cloud", "cockroach.silkky.cloud", "traefik.silkky.cloud", "admin.silkky.cloud"]
      policy: two_factor
#      networks:
#        - main.web
      subject:
        - "group:admin"

notifier:
  smtp:
    host: smtp.eu.mailgun.org
    port: 587
    username: noreply@robot.silkky.cloud
    sender: "Authelia <noreply@rebot.silkky.cloud>"
    subject: "[Authelia] {title}"

regulation:
  max_retries: 2
  find_time: 5m
  ban_time: 1d

storage:
  local:
    path: /data/db.sqlite3

session:
  domain: silkky.cloud
  expiration: 1h
  redis:
    host: redis
    port: 6379

authentication_backend:
  disable_reset_password: true
  file:
    path: /data/users.yml
    password:
      algorithm: argon2id