http:
  middlewares:
    # Default security headers
    secureHeaders:
      headers:
        # Strict-Transport-Security
        stsSeconds: 31536000
        stsIncludeSubdomains: true
        stsPreload: true
        # X-XSS-Protection
        browserXssFilter: true
        # X-Content-Type-Options
        contentTypeNosniff: true
        # Referrer-Policy
        referrerPolicy: "strict-origin-when-cross-origin"
        # Block Google FLoC
        permissionsPolicy: "interest-cohort=()"

  routers:
    cockroachdb-admin:
      rule: "Host(`cockroach.silkky.cloud`)"
      entryPoints:
        - websecure
      tls: {}
      middlewares:
        - authelia@docker
      service: cockroachdb-admin-service@file

  serversTransports:
    cockroachdb-admin:
      insecureSkipVerify: true

  services:
    cockroachdb-admin-service:
      loadBalancer:
        servers:
          - url: "https://cockroachdb-1:8080"
        serversTransport: cockroachdb-admin@file

tls:
  options:
    default:
      minVersion: VersionTLS12
  certificates:
    - certFile: /run/secrets/origin.crt
      keyFile: /run/secrets/origin.key
    # Piped
    - certFile: /run/secrets/piped.crt
      keyFile: /run/secrets/piped.key